# backend/wrangler.toml
name = "bridge-aggregator-api"
main = "workers/api.js"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = true

[env.production.vars]
# Add any API keys here
# SOCKET_API_KEY = "your_key"
# PARASWAP_API_KEY = "your_key"